"""Add gamification fields

Revision ID: 6f236301d85d
Revises: cd243a222842
Create Date: 2025-09-06 17:36:36.064906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f236301d85d'
down_revision = 'cd243a222842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('total_days_logged', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_days_logged')
        batch_op.drop_column('last_login_date')

    # ### end Alembic commands ###
